application: bsi-pto
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /paypal-ipn
  script: bsigala.app
  secure: always

- url: /sheet-test
  script: bsigala.app
  secure: always

- url: /submit-ad
  script: bsigala.app
  secure: always

- url: /c/
  static_dir: bower_components
  secure: always

- url: /$
  static_files: site/index.html
  upload: site/index.html
  secure: always
  mime_type: text/html; charset=UTF-8

- url: /
  static_dir: site
  secure: always

- url: /.*\.html$
  static_dir: site
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"
- name: pycrypto
  version: "2.6"
